import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";

import { CommandMenu } from "@/components/layout/command-menu";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Design System",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <body className={`${inter.className} flex flex-col items-center justify-center gap-4 min-h-screen bg-black`}>
        <CommandMenu />

        <main className="max-w-[648px] w-full">{children}</main>
      </body>
    </html>
  );
}
